# A generic, single database configuration.

[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql://postgres:postgres@localhost:5433/temposort

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the execution date
# within the migration file, can be set to timezone or offset
# timezone =

# max length of revision ids in Alembic
# revision_environment = false

# set to 'true' to run the migration in 'check' mode
# check = false

# version_locations =

# set to 'true' to run migration in 'sql' mode
# sql = false

# set to 'true' to run with async support
# async_mode = true

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
,datefmt = %Y-%m-%d %H:%M:%S
