"""initial_schema

Revision ID: 8fe4053ad719
Revises: 
Create Date: 2026-09-26 03:29:46.967001
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe4053ad719'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminders', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('reminders', 'user_email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reminders', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('reminders', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.alter_column('reminders', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_reminders_user_email'), 'reminders', ['user_email'], unique=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('tasks', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('verification_tokens', 'token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('verification_tokens', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_verification_tokens_email'), 'verification_tokens', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_email'), table_name='verification_tokens')
    op.alter_column('verification_tokens', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('verification_tokens', 'token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::text"))
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_reminders_user_email'), table_name='reminders')
    op.alter_column('reminders', 'channel',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reminders', 'message',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reminders', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reminders', 'user_email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reminders', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
